- id: cargo-audit
  name: cargo-audit
  description: Check Cargo dependencies
  entry: cargo-audit
  language: system
  types: [file, toml]
  files: Cargo\.(toml|lock)
  pass_filenames: false
- id: cbindgen-verify
  name: cbindgen-verify
  description: Check that cbindgen bindings were generated correctly
  entry: cbindgen
  language: system
  types_or: [rust, toml, header]
  pass_filenames: false
  # At least, you'll need to add the following arguments
  # args: ["--verify", "--output", "<your-generated-file.h>"]
